package boilerplate

const MAIN_PY = `from website import create_app

app = create_app()

if __name__ == "__main__":
    app.run(debug=True)
`

const INIT_PY = `from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "replace with your own"

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    return app
`

const BASE_HTML = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{%block title%}{%endblock%}</title>
    <link href="{{url_for('static', filename='style.css')}}" rel="stylesheet">
  </head>
  <body>
    <main>
      {%block content%}
      {%endblock%}
    </main>
  </body>
</html>
`

const INDEX_HTML = `{%extends 'base.html'%}

{%block title%}Vial app {%endblock%}

{%block content%}
<p>This app was generated by Vial!</p>
<b>Version 0.1</b>
{%endblock%}
`

const VIEWS_PY = `from flask import Blueprint, render_template

views = Blueprint("views", __name__)

@views.route("/")
def home():
    return render_template("index.html")


`

const AUTH_PY = `from flask import Blueprint, render_template

auth = Blueprint("auth", __name__)


`

const REQUIREMENTS_TXT = `flask
gunicorn`
